name: Angular App to Azure

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: RoutingApp.UI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Show current branch
        run: |
          echo "Branch: ${{ github.ref }}"

      - name: Copy environment file
        run: cp src/environments/environment.example.ts src/environments/environment.ts

      - name: Update environment.ts with secrets
        run: |
          sed -i "s|domain: ''|domain: '${{ secrets.AUTH0_DOMAIN }}'|g" src/environments/environment.ts
          sed -i "s|clientId: ''|clientId: '${{ secrets.AUTH0_CLIENT_ID }}'|g" src/environments/environment.ts
          sed -i "s|audience: 'api link'|audience: '${{ secrets.AUTH0_AUDIENCE }}'|g" src/environments/environment.ts
          sed -i "s|redirectUri: ''|redirectUri: '${{ secrets.AUTH0_REDIRECT_URI }}'|g" src/environments/environment.ts
    
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm ci

      - name: Build the Angular app
        run: npm run build

      - name: Confirm build contents
        run: ls -la dist/RoutingApp.UI/browser

      - name: Zip build output
        run: |
          cd dist/RoutingApp.UI/browser
          zip -r ../../../build.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "routing-app-ui"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build.zip #RoutingApp.UI/dist/RoutingApp.UI/browser
